name: cloudflare

on:
  push:
    branches: [ master ]

jobs:
  clear-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Cloudflare Purge Cache
        uses: jakejarvis/cloudflare-purge-action@eee6dba0236093358f25bb1581bd615dc8b3d8e3
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
